apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-min-side
  namespace: min-side
  labels:
    team: min-side
  annotations:
    config.linkerd.io/proxy-memory-limit: "512Mi"
    config.linkerd.io/proxy-memory-request: "128Mi"
spec:
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
  tokenx:
    enabled: true
  envFrom:
    - secret: tms-min-side-secrets
  image: {{image}}
  port: 3000
  liveness:
    path: /minside/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /minside/api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 6
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  ingresses:
    - "https://www.intern.nav.no/minside"
    - "https://www.nav.no/minside"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 128Mi
